import { Routes } from '@angular/router';
import { accountGuard, adminGuard, adminLegacyTabGuard } from './services/auth.guard';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home.component').then((m) => m.HomeComponent) },
  { path: 'category/:slug', loadComponent: () => import('./pages/catalog.pages').then((m) => m.CategoryComponent) },
  { path: 'listing/:slug', loadComponent: () => import('./pages/catalog.pages').then((m) => m.ListingComponent) },
  { path: 'product/:slug', loadComponent: () => import('./pages/product.page').then((m) => m.ProductPageComponent) },
  { path: 'cart', redirectTo: '', pathMatch: 'full' },
  { path: 'checkout', loadComponent: () => import('./pages/checkout.pages').then((m) => m.CheckoutPageComponent) },
  { path: 'order/confirmed', loadComponent: () => import('./pages/checkout.pages').then((m) => m.OrderConfirmedComponent) },
  { path: 'account', redirectTo: 'account/overview', pathMatch: 'full' },
  { path: 'account/:tab', canActivate: [accountGuard], loadComponent: () => import('./pages/account.pages').then((m) => m.AccountPageComponent) },
  { path: 'admin', canActivate: [adminGuard], loadComponent: () => import('./pages/admin.page').then((m) => m.AdminPageComponent) },
  { path: 'admin/:tab', canActivate: [adminGuard, adminLegacyTabGuard], children: [] },
  { path: 'login', loadComponent: () => import('./pages/auth.page').then((m) => m.AuthPageComponent) },
  { path: 'signup', loadComponent: () => import('./pages/auth.page').then((m) => m.AuthPageComponent) },
  { path: 'search', loadComponent: () => import('./pages/catalog.pages').then((m) => m.SearchComponent) },
  { path: 'wishlist', loadComponent: () => import('./pages/account.pages').then((m) => m.WishlistPageComponent) },
  { path: 'compare', loadComponent: () => import('./pages/compare.page').then((m) => m.ComparePageComponent) },
  { path: 'offers', loadComponent: () => import('./pages/catalog.pages').then((m) => m.OffersComponent) },
  { path: 'new', loadComponent: () => import('./pages/catalog.pages').then((m) => m.OffersComponent) },
  { path: 'track', loadComponent: () => import('./pages/checkout.pages').then((m) => m.TrackPageComponent) },
  { path: 'about', loadComponent: () => import('./pages/content.pages').then((m) => m.AboutPageComponent) },
  { path: 'support', loadComponent: () => import('./pages/content.pages').then((m) => m.SupportPageComponent) },
  { path: 'faq', loadComponent: () => import('./pages/content.pages').then((m) => m.FaqPageComponent) },
  { path: 'maintenance', loadComponent: () => import('./pages/content.pages').then((m) => m.MaintenancePageComponent) },
  { path: 'shop', redirectTo: 'listing/all', pathMatch: 'full' },
  { path: 'track-order', redirectTo: 'track', pathMatch: 'full' },
  { path: 'register', redirectTo: 'signup', pathMatch: 'full' },
  { path: 'contact', redirectTo: 'support', pathMatch: 'full' },
  { path: 'home', redirectTo: '', pathMatch: 'full' },
  { path: '**', loadComponent: () => import('./pages/content.pages').then((m) => m.NotFoundPageComponent) },
];
